CREATE SEQUENCE COLETA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE T_COL_AGENDAMENTO_COLETA (
    id_agendamento INTEGER DEFAULT COLETA_SEQ.NEXTVAL NOT NULL,
    dt_agendamento TIMESTAMP NOT NULL,
    status CHAR(1),
);

ALTER TABLE T_COL_AGENDAMENTO_COLETA ADD CONSTRAINT T_COL_AGENDAMENTO_COLETA_pk PRIMARY KEY ( id_agendamento );